export const LOGIC_QUESTIONS = [
  { text: 'Sở thú bị cháy, con gì chạy ra đầu tiên?', answer: 'Con người', options: ['Con người', 'Con khỉ', 'Con chim', 'Con rắn'] },
  { text: 'Bệnh gì bác sĩ bó tay?', answer: 'Gãy tay', options: ['Gãy tay', 'Đau đầu', 'Sổ mũi', 'Đau dạ dày'] },
  { text: 'Con gì đập thì sống, không đập thì chết?', answer: 'Con tim', options: ['Con tim', 'Con muỗi', 'Con ruồi', 'Con kiến'] },
  { text: 'Cái gì người mua biết, người bán biết, người xài không bao giờ biết?', answer: 'Quan tài', options: ['Quan tài', 'Áo quần', 'Đồ ăn', 'Vàng bạc'] },
  { text: 'Hai người đào rãnh trong 2 giờ. Hỏi 1 người đào rãnh đó trong bao lâu?', answer: '4 giờ', options: ['4 giờ', '1 giờ', '2 giờ', '8 giờ'] },
  { text: 'Tháng nào có 28 ngày?', answer: 'Tháng nào cũng có', options: ['Tháng nào cũng có', 'Tháng 2', 'Tháng 4', 'Tháng 8'] },
  { text: 'Bỏ ngoài nướng trong, ăn ngoài bỏ trong là bắp ngô. Đúng hay sai?', answer: 'Đúng', options: ['Đúng', 'Sai', 'Không biết', 'Tùy loại ngô'] },
  { text: 'Làm thế nào để con cua được 9 chân?', answer: 'Luộc chín', options: ['Luộc chín', 'Cắt 1 chân', 'Thêm 1 chân', 'Không thể'] },
  { text: 'Lịch nào dài nhất?', answer: 'Lịch sử', options: ['Lịch sử', 'Lịch vạn niên', 'Lịch treo tường', 'Lịch để bàn'] },
  { text: 'Xã đông nhất là xã nào?', answer: 'Xã hội', options: ['Xã hội', 'Xã đàn', 'Xã giao', 'Xã xệ'] },
  { text: 'Con đường dài nhất là đường nào?', answer: 'Đường đời', options: ['Đường đời', 'Đường xích đạo', 'Đường cao tốc', 'Đường hầm'] },
  { text: 'Quần rộng nhất là quần gì?', answer: 'Quần đảo', options: ['Quần đảo', 'Quần ống loe', 'Quần đùi', 'Quần thụng'] },
  { text: 'Cây gì có 1 lá?', answer: 'Cờ', options: ['Cờ', 'Cây bàng', 'Cây chuối', 'Cây dừa'] },
  { text: 'Môn gì càng thắng càng thua?', answer: 'Đua xe đạp', options: ['Đua xe đạp', 'Kéo co', 'Bóng đá', 'Cờ vua'] },
  { text: 'Con gì đầu dê mình ốc?', answer: 'Con dốc', options: ['Con dốc', 'Con ốc sên', 'Con rùa', 'Con dê'] },
  { text: 'Nắng ba năm ta chưa hề bỏ bạn?', answer: 'Cái bóng', options: ['Cái bóng', 'Cái nón', 'Cái áo', 'Cái ô'] },
  { text: 'Cái gì đen khi mua, đỏ khi dùng, xám khi vứt?', answer: 'Than', options: ['Than', 'Củi', 'Giấy', 'Diêm'] },
  { text: 'Cắm vào run rẩy toàn thân... là cái gì?', answer: 'Tủ lạnh', options: ['Tủ lạnh', 'Máy giặt', 'Quạt trần', 'Bàn ủi'] },
  { text: 'Bánh gì không ăn được?', answer: 'Bánh xe', options: ['Bánh xe', 'Bánh xà phòng', 'Bánh đúc', 'Bánh gai'] },
  { text: 'Hoa gì biết ăn, biết nói?', answer: 'Hoa hậu', options: ['Hoa hậu', 'Hoa hồng', 'Hoa lan', 'Hoa súng'] },
  { text: 'Có 1 đàn chim đậu trên cành, người thợ săn bắn cái rằm. Hỏi còn mấy con?', answer: '0 con', options: ['0 con', '1 con', '15 con', 'Tất cả'] },
  { text: 'Con trai có gì quý nhất?', answer: 'Ngọc trai', options: ['Ngọc trai', 'Sức khỏe', 'Trí tuệ', 'Vàng bạc'] },
  { text: 'Trò gì càng chơi càng ra nước?', answer: 'Cờ vua', options: ['Cờ vua', 'Bơi lội', 'Kéo co', 'Trốn tìm'] },
  { text: 'Nơi nào có đường xá, nhưng không có xe cộ?', answer: 'Bản đồ', options: ['Bản đồ', 'Sa mạc', 'Rừng sâu', 'Đại dương'] },
  { text: 'Cái gì bạn không mượn mà trả?', answer: 'Lời cảm ơn', options: ['Lời cảm ơn', 'Tiền bạc', 'Tình cảm', 'Đồ đạc'] },
  { text: 'Cái gì luôn đi đến mà không bao giờ đến nơi?', answer: 'Ngày mai', options: ['Ngày mai', 'Tương lai', 'Thời gian', 'Cơn gió'] },
  { text: 'Cái gì của bạn nhưng người khác dùng nhiều hơn bạn?', answer: 'Tên của bạn', options: ['Tên của bạn', 'Tiền của bạn', 'Nhà của bạn', 'Xe của bạn'] },
  { text: 'Con gì mang được miếng gỗ lớn nhưng không mang được hòn sỏi?', answer: 'Con sông', options: ['Con sông', 'Con voi', 'Con kiến', 'Con trâu'] },
  { text: 'Cái gì có kích thước bằng con voi nhưng chẳng nặng gram nào?', answer: 'Bóng con voi', options: ['Bóng con voi', 'Đám mây', 'Quả bóng bay', 'Mô hình voi'] },
  { text: 'Từ nào trong từ điển viết sai chính tả?', answer: 'Từ "sai"', options: ['Từ "sai"', 'Từ "đúng"', 'Không có từ nào', 'Từ "chính tả"'] },
  { text: 'Tôi có 4 chân nhưng không biết đi. Tôi là ai?', answer: 'Cái bàn', options: ['Cái bàn', 'Con chó', 'Con mèo', 'Cái ghế'] },
  { text: 'Có cổ nhưng không có đầu. Là cái gì?', answer: 'Cái áo', options: ['Cái áo', 'Cái chai', 'Con hươu', 'Cái bình'] },
  { text: 'Có răng nhưng không cắn được ai. Là cái gì?', answer: 'Cái lược', options: ['Cái lược', 'Cái cưa', 'Con cá sấu', 'Bánh răng'] },
  { text: 'Cái gì càng kéo càng ngắn?', answer: 'Điếu thuốc', options: ['Điếu thuốc', 'Sợi dây', 'Cái kẹo', 'Tuổi thọ'] },
  { text: 'Cái gì đánh cha, đánh má, đánh anh, đánh chị?', answer: 'Bàn chải đánh răng', options: ['Bàn chải đánh răng', 'Cái roi', 'Cái chổi', 'Cái gậy'] },
  { text: 'Con mèo nào cực kỳ sợ chuột?', answer: 'Doraemon', options: ['Doraemon', 'Tom', 'Mèo máy', 'Mèo rừng'] },
  { text: 'Người đàn ông duy nhất trên thế giới có sữa là ai?', answer: 'Ông Thọ', options: ['Ông Thọ', 'Bác sĩ', 'Người cha', 'Không có ai'] },
  { text: 'Cái gì Adam có 2 mà Eva chỉ có 1?', answer: 'Chữ A', options: ['Chữ A', 'Con mắt', 'Cái tay', 'Quả táo'] },
  { text: 'Khi Beckham thực hiện quả đá phạt đền, anh ta sẽ sút vào đâu?', answer: 'Quả bóng', options: ['Quả bóng', 'Khung thành', 'Thủ môn', 'Lưới'] },
  { text: 'Có bao nhiêu chữ C trong câu: "Cơm, canh, cháo gì tớ cũng thích ăn!"?', answer: '1 chữ C', options: ['1 chữ C', '2 chữ C', '3 chữ C', '4 chữ C'] },
];

export const GENZ_QUESTIONS = [
  { text: 'Cái gì càng thiu càng ngon?', answer: 'Giấc ngủ', options: ['Giấc ngủ', 'Bánh mì', 'Cơm nguội', 'Canh chua'] },
  { text: 'Con gì sinh ra đã được làm vua?', answer: 'Con cua', options: ['Con cua', 'Con rồng', 'Con hổ', 'Con sư tử'] },
  { text: 'Cái gì càng cất càng thấy?', answer: 'Cái nhà', options: ['Cái nhà', 'Tiền bạc', 'Bí mật', 'Đồ ăn'] },
  { text: 'Cái gì càng rửa càng bẩn?', answer: 'Nước', options: ['Nước', 'Cái chậu', 'Cái khăn', 'Cái tay'] },
  { text: 'Trái gì không ăn được mà ai cũng sợ?', answer: 'Trái tính trái nết', options: ['Trái tính trái nết', 'Trái sầu riêng', 'Trái ớt', 'Trái mướp đắng'] },
  { text: 'Cái gì càng nặng càng nhẹ?', answer: 'Cái cân', options: ['Cái cân', 'Đám mây', 'Cái bóng', 'Kỷ niệm'] },
  { text: 'Cái gì càng thêm càng thiếu?', answer: 'Cái hố', options: ['Cái hố', 'Tiền bạc', 'Kiến thức', 'Tình cảm'] },
  { text: 'Cái gì càng cao càng thấp?', answer: 'Cái thang', options: ['Cái thang', 'Ngọn núi', 'Cái cây', 'Tòa nhà'] },
  { text: 'Cái gì càng bẩn càng trắng?', answer: 'Cái bảng đen', options: ['Cái bảng đen', 'Cái áo', 'Cái răng', 'Cái gương'] },
  { text: 'Cái gì càng gầy càng béo?', answer: 'Cái nến', options: ['Cái nến', 'Con heo', 'Cái cây', 'Con người'] },
  { text: 'Cái gì càng mất càng được?', answer: 'Kinh nghiệm', options: ['Kinh nghiệm', 'Tiền bạc', 'Thời gian', 'Sức khỏe'] },
  { text: 'Cái gì có mặt mà không có đầu?', answer: 'Đồng hồ', options: ['Đồng hồ', 'Cái bàn', 'Cái ghế', 'Cái gương'] },
  { text: 'Cái gì càng chạy càng đứng?', answer: 'Đồng hồ', options: ['Đồng hồ', 'Con người', 'Xe cộ', 'Dòng sông'] },
  { text: 'Cái gì có chân mà không có tay, có thân mà không có đầu?', answer: 'Cái quần', options: ['Cái quần', 'Cái bàn', 'Cái ghế', 'Cây cối'] },
  { text: 'Cái gì càng tối càng sáng?', answer: 'Cái đèn', options: ['Cái đèn', 'Con mắt', 'Bầu trời', 'Bóng đêm'] },
  { text: 'Cái gì càng thắng càng thua?', answer: 'Đua xe đạp', options: ['Đua xe đạp', 'Kéo co', 'Bóng đá', 'Cờ vua'] },
  { text: 'Cái gì càng chơi càng ra nước?', answer: 'Cờ vua', options: ['Cờ vua', 'Bơi lội', 'Kéo co', 'Trốn tìm'] },
  { text: 'Cái gì Adam có 2 mà Eva chỉ có 1?', answer: 'Chữ A', options: ['Chữ A', 'Con mắt', 'Cái tay', 'Quả táo'] },
  { text: 'Từ nào trong từ điển viết sai chính tả?', answer: 'Từ "sai"', options: ['Từ "sai"', 'Từ "đúng"', 'Không có từ nào', 'Từ "chính tả"'] },
  { text: 'Con mèo nào cực kỳ sợ chuột?', answer: 'Doraemon', options: ['Doraemon', 'Tom', 'Mèo máy', 'Mèo rừng'] },
  { text: 'Cái gì càng kéo càng ngắn?', answer: 'Điếu thuốc', options: ['Điếu thuốc', 'Sợi dây', 'Cái kẹo', 'Tuổi thọ'] },
  { text: 'Cái gì đánh cha, đánh má, đánh anh, đánh chị?', answer: 'Bàn chải đánh răng', options: ['Bàn chải đánh răng', 'Cái roi', 'Cái chổi', 'Cái gậy'] },
  { text: 'Người đàn ông duy nhất trên thế giới có sữa là ai?', answer: 'Ông Thọ', options: ['Ông Thọ', 'Bác sĩ', 'Người cha', 'Không có ai'] },
  { text: 'Cái gì đen khi mua, đỏ khi dùng, xám khi vứt?', answer: 'Than', options: ['Than', 'Củi', 'Giấy', 'Diêm'] },
  { text: 'Cái gì có cổ nhưng không có đầu?', answer: 'Cái áo', options: ['Cái áo', 'Cái chai', 'Con hươu', 'Cái bình'] },
  { text: 'Cái gì có răng nhưng không cắn được ai?', answer: 'Cái lược', options: ['Cái lược', 'Cái cưa', 'Con cá sấu', 'Bánh răng'] },
  { text: 'Cái gì càng già càng trẻ?', answer: 'Cái bóng', options: ['Cái bóng', 'Con người', 'Cái cây', 'Bức ảnh'] },
  { text: 'Trái gì tên nghe đã thấy đau?', answer: 'Trái khổ qua', options: ['Trái khổ qua', 'Trái ớt', 'Trái sầu riêng', 'Trái mướp đắng'] },
  { text: 'Con gì không bao giờ biết đi?', answer: 'Con đường', options: ['Con đường', 'Con cá', 'Con rắn', 'Con chim'] },
  { text: 'Cái gì có miệng mà không nói, có giường mà không ngủ?', answer: 'Con sông', options: ['Con sông', 'Cái hang', 'Cái hố', 'Cái chai'] },
];

export const PROVERB_QUESTIONS = [
  { text: 'Điền vào chỗ trống: "Gần mực thì đen, gần đèn thì..."', answer: 'Sáng', options: ['Sáng', 'Chói', 'Tối', 'Lòa'] },
  { text: 'Điền vào chỗ trống: "Có công mài sắt, có ngày nên..."', answer: 'Kim', options: ['Kim', 'Dao', 'Kéo', 'Búa'] },
  { text: 'Điền vào chỗ trống: "Ăn quả nhớ kẻ trồng..."', answer: 'Cây', options: ['Cây', 'Hoa', 'Trái', 'Rừng'] },
  { text: 'Điền vào chỗ trống: "Uống nước nhớ..."', answer: 'Nguồn', options: ['Nguồn', 'Suối', 'Sông', 'Biển'] },
  { text: 'Điền vào chỗ trống: "Tốt gỗ hơn tốt nước..."', answer: 'Sơn', options: ['Sơn', 'Màu', 'Bóng', 'Hoa'] },
  { text: 'Điền vào chỗ trống: "Một con ngựa đau cả tàu bỏ..."', answer: 'Cỏ', options: ['Cỏ', 'Ăn', 'Chạy', 'Ngủ'] },
  { text: 'Điền vào chỗ trống: "Cái nết đánh chết cái..."', answer: 'Đẹp', options: ['Đẹp', 'Xấu', 'Duyên', 'Tình'] },
  { text: 'Điền vào chỗ trống: "Đi một ngày đàng, học một sàng..."', answer: 'Khôn', options: ['Khôn', 'Dại', 'Sách', 'Chữ'] },
  { text: 'Điền vào chỗ trống: "Lá lành đùm lá..."', answer: 'Rách', options: ['Rách', 'Nát', 'Khô', 'Vàng'] },
  { text: 'Điền vào chỗ trống: "Gieo gió gặt..."', answer: 'Bão', options: ['Bão', 'Mưa', 'Nắng', 'Sấm'] },
  { text: 'Điền vào chỗ trống: "Kiến tha lâu cũng đầy..."', answer: 'Tổ', options: ['Tổ', 'Nhà', 'Hang', 'Đất'] },
  { text: 'Điền vào chỗ trống: "Tức nước vỡ..."', answer: 'Bờ', options: ['Bờ', 'Đê', 'Đập', 'Chậu'] },
  { text: 'Điền vào chỗ trống: "Ở hiền gặp..."', answer: 'Lành', options: ['Lành', 'Tốt', 'May', 'Phúc'] },
  { text: 'Điền vào chỗ trống: "Áo mặc sao qua khỏi..."', answer: 'Đầu', options: ['Đầu', 'Cổ', 'Tay', 'Lưng'] },
  { text: 'Điền vào chỗ trống: "Con hơn cha là nhà có..."', answer: 'Phúc', options: ['Phúc', 'Lộc', 'Tài', 'Đức'] },
  { text: 'Điền vào chỗ trống: "Giỏ nhà ai quai nhà..."', answer: 'Nấy', options: ['Nấy', 'Đ đó', 'Kia', 'Này'] },
  { text: 'Điền vào chỗ trống: "Tránh vỏ dưa gặp vỏ..."', answer: 'Dừa', options: ['Dừa', 'Chuối', 'Cam', 'Bưởi'] },
  { text: 'Điền vào chỗ trống: "Thất bại là mẹ..."', answer: 'Thành công', options: ['Thành công', 'Chiến thắng', 'Kinh nghiệm', 'Bài học'] },
  { text: 'Điền vào chỗ trống: "Nước mắt chảy..."', answer: 'Xuôi', options: ['Xuôi', 'Ngược', 'Tràn', 'Dài'] },
  { text: 'Điền vào chỗ trống: "Môi hở răng..."', answer: 'Lạnh', options: ['Lạnh', 'Buốt', 'Đau', 'Rụng'] },
  { text: 'Điền vào chỗ trống: "Lửa thử vàng, gian nan thử..."', answer: 'Sức', options: ['Sức', 'Tài', 'Trí', 'Lòng'] },
  { text: 'Điền vào chỗ trống: "Thuận vợ thuận chồng tát biển Đông cũng..."', answer: 'Cạn', options: ['Cạn', 'Khô', 'Vơi', 'Hết'] },
  { text: 'Điền vào chỗ trống: "Ăn vóc học..."', answer: 'Hay', options: ['Hay', 'Tài', 'Giỏi', 'Khôn'] },
  { text: 'Điền vào chỗ trống: "Học thầy không tày học..."', answer: 'Bạn', options: ['Bạn', 'Sách', 'Đời', 'Trường'] },
  { text: 'Điền vào chỗ trống: "Trăm hay không bằng tay..."', answer: 'Quen', options: ['Quen', 'Làm', 'Giỏi', 'Nhanh'] },
  { text: 'Điền vào chỗ trống: "Lời nói gói..."', answer: 'Vàng', options: ['Vàng', 'Bạc', 'Tiền', 'Ngọc'] },
  { text: 'Điền vào chỗ trống: "Chim có tổ, người có..."', answer: 'Tông', options: ['Tông', 'Nhà', 'Quê', 'Cội'] },
  { text: 'Điền vào chỗ trống: "Đói cho sạch, rách cho..."', answer: 'Thơm', options: ['Thơm', 'Lành', 'Đẹp', 'Mới'] },
  { text: 'Điền vào chỗ trống: "Giấy rách phải giữ lấy..."', answer: 'Lề', options: ['Lề', 'Góc', 'Mép', 'Chữ'] },
  { text: 'Điền vào chỗ trống: "Một cây làm chẳng nên..."', answer: 'Non', options: ['Non', 'Rừng', 'Núi', 'Cảnh'] },
  { text: 'Điền vào chỗ trống: "Ba cây chụm lại nên hòn núi..."', answer: 'Cao', options: ['Cao', 'To', 'Lớn', 'Đẹp'] },
  { text: 'Điền vào chỗ trống: "Bán anh em xa mua láng giềng..."', answer: 'Gần', options: ['Gần', 'Thân', 'Tốt', 'Quen'] },
  { text: 'Điền vào chỗ trống: "Lên thác xuống..."', answer: 'Ghềnh', options: ['Ghềnh', 'Đèo', 'Suối', 'Sông'] },
  { text: 'Điền vào chỗ trống: "Mật ngọt chết..."', answer: 'Ruồi', options: ['Ruồi', 'Kiến', 'Ong', 'Muỗi'] },
  { text: 'Điền vào chỗ trống: "Chớp đông nhay nháy, gà gáy thì..."', answer: 'Mưa', options: ['Mưa', 'Nắng', 'Bão', 'Gió'] },
  { text: 'Điền vào chỗ trống: "Chuồn chuồn bay thấp thì mưa, bay cao thì nắng, bay vừa thì..."', answer: 'Râm', options: ['Râm', 'Mát', 'Gió', 'Bão'] },
  { text: 'Điền vào chỗ trống: "Cơn đằng Đông vừa trông vừa chạy, cơn đằng Nam vừa làm vừa..."', answer: 'Chơi', options: ['Chơi', 'Nghỉ', 'Hát', 'Cười'] },
  { text: 'Điền vào chỗ trống: "Lúa chiêm lấp ló đầu bờ, hễ nghe tiếng sấm phất cờ mà..."', answer: 'Lên', options: ['Lên', 'Trổ', 'Chín', 'Mọc'] },
  { text: 'Điền vào chỗ trống: "Đêm tháng năm chưa nằm đã sáng, ngày tháng mười chưa cười đã..."', answer: 'Tối', options: ['Tối', 'Khóc', 'Buồn', 'Ngủ'] },
  { text: 'Điền vào chỗ trống: "Gió heo may, chuồn chuồn bay thì..."', answer: 'Bão', options: ['Bão', 'Mưa', 'Nắng', 'Rét'] },
];
