export const LOGIC_QUESTIONS = [
  { text: 'Sở thú bị cháy, con gì chạy ra đầu tiên?', answer: 'Con người', options: ['Con người', 'Con khỉ', 'Con chim', 'Con rắn'], explanation: 'Vì con người có trí thông minh và biết sợ hãi nhất khi thấy cháy!' },
  { text: 'Bệnh gì bác sĩ bó tay?', answer: 'Gãy tay', options: ['Gãy tay', 'Đau đầu', 'Sổ mũi', 'Đau dạ dày'], explanation: 'Khi bị gãy tay, bác sĩ phải dùng thạch cao để "bó tay" lại cho xương mau lành.' },
  { text: 'Con gì đập thì sống, không đập thì chết?', answer: 'Con tim', options: ['Con tim', 'Con muỗi', 'Con ruồi', 'Con kiến'], explanation: 'Tim phải đập liên tục để duy trì sự sống cho cơ thể.' },
  { text: 'Cái gì người mua biết, người bán biết, người xài không bao giờ biết?', answer: 'Quan tài', options: ['Quan tài', 'Áo quần', 'Đồ ăn', 'Vàng bạc'], explanation: 'Người xài quan tài là người đã khuất nên không thể biết mình đang xài nó.' },
  { text: 'Hai người đào rãnh trong 2 giờ. Hỏi 1 người đào rãnh đó trong bao lâu?', answer: '4 giờ', options: ['4 giờ', '1 giờ', '2 giờ', '8 giờ'], explanation: 'Giả sử năng suất như nhau, 1 người sẽ mất gấp đôi thời gian so với 2 người.' },
  { text: 'Tháng nào có 28 ngày?', answer: 'Tháng nào cũng có', options: ['Tháng nào cũng có', 'Tháng 2', 'Tháng 4', 'Tháng 8'], explanation: 'Tất cả 12 tháng trong năm đều có ít nhất 28 ngày.' },
  { text: 'Bỏ ngoài nướng trong, ăn ngoài bỏ trong là bắp ngô. Đúng hay sai?', answer: 'Đúng', options: ['Đúng', 'Sai', 'Không biết', 'Tùy loại ngô'], explanation: 'Bỏ vỏ (ngoài), nướng hạt (trong), ăn hạt (ngoài), bỏ lõi (trong).' },
  { text: 'Làm thế nào để con cua được 9 chân?', answer: 'Luộc chín', options: ['Luộc chín', 'Cắt 1 chân', 'Thêm 1 chân', 'Không thể'], explanation: 'Cua luộc "chín" (9) là cách chơi chữ trong tiếng Việt.' },
  { text: 'Lịch nào dài nhất?', answer: 'Lịch sử', options: ['Lịch sử', 'Lịch vạn niên', 'Lịch treo tường', 'Lịch để bàn'], explanation: 'Lịch sử kéo dài từ quá khứ xa xôi đến tận tương lai.' },
  { text: 'Xã đông nhất là xã nào?', answer: 'Xã hội', options: ['Xã hội', 'Xã đàn', 'Xã giao', 'Xã xệ'], explanation: 'Xã hội bao gồm tất cả mọi người nên là "xã" đông nhất.' },
  { text: 'Con đường dài nhất là đường nào?', answer: 'Đường đời', options: ['Đường đời', 'Đường xích đạo', 'Đường cao tốc', 'Đường hầm'], explanation: 'Đường đời kéo dài suốt cuộc đời của một con người.' },
  { text: 'Quần rộng nhất là quần gì?', answer: 'Quần đảo', options: ['Quần đảo', 'Quần ống loe', 'Quần đùi', 'Quần thụng'], explanation: 'Quần đảo là một tập hợp các hòn đảo trên biển, diện tích rất lớn.' },
  { text: 'Cây gì có 1 lá?', answer: 'Cờ', options: ['Cờ', 'Cây bàng', 'Cây chuối', 'Cây dừa'], explanation: 'Cây cờ chỉ có một lá cờ treo trên đỉnh.' },
  { text: 'Môn gì càng thắng càng thua?', answer: 'Đua xe đạp', options: ['Đua xe đạp', 'Kéo co', 'Bóng đá', 'Cờ vua'], explanation: 'Trong đua xe đạp, "thắng" nghĩa là bóp phanh, làm xe chậm lại (thua).' },
  { text: 'Con gì đầu dê mình ốc?', answer: 'Con dốc', options: ['Con dốc', 'Con ốc sên', 'Con rùa', 'Con dê'], explanation: 'Chữ "Dốc" ghép từ "Dê" (đầu) và "Ốc" (mình).' },
  { text: 'Nắng ba năm ta chưa hề bỏ bạn?', answer: 'Cái bóng', options: ['Cái bóng', 'Cái nón', 'Cái áo', 'Cái ô'], explanation: 'Khi có nắng, cái bóng luôn đi theo sát bên cạnh bạn.' },
  { text: 'Cái gì đen khi mua, đỏ khi dùng, xám khi vứt?', answer: 'Than', options: ['Than', 'Củi', 'Giấy', 'Diêm'], explanation: 'Than đá màu đen, khi cháy đỏ rực, khi tàn thành tro xám.' },
  { text: 'Cắm vào run rẩy toàn thân... là cái gì?', answer: 'Tủ lạnh', options: ['Tủ lạnh', 'Máy giặt', 'Quạt trần', 'Bàn ủi'], explanation: 'Khi cắm điện, tủ lạnh sẽ rung nhẹ và làm mọi thứ bên trong lạnh (run rẩy).' },
  { text: 'Bánh gì không ăn được?', answer: 'Bánh xe', options: ['Bánh xe', 'Bánh xà phòng', 'Bánh đúc', 'Bánh gai'], explanation: 'Bánh xe dùng để di chuyển, không phải thực phẩm.' },
  { text: 'Hoa gì biết ăn, biết nói?', answer: 'Hoa hậu', options: ['Hoa hậu', 'Hoa hồng', 'Hoa lan', 'Hoa súng'], explanation: 'Hoa hậu là con người, nên biết ăn và biết nói.' },
  { text: 'Có 1 đàn chim đậu trên cành, người thợ săn bắn cái rằm. Hỏi còn mấy con?', answer: '0 con', options: ['0 con', '1 con', '15 con', 'Tất cả'], explanation: 'Tiếng súng nổ làm cả đàn chim sợ hãi bay đi hết.' },
  { text: 'Con trai có gì quý nhất?', answer: 'Ngọc trai', options: ['Ngọc trai', 'Sức khỏe', 'Trí tuệ', 'Vàng bạc'], explanation: 'Ngọc trai là sản vật quý giá nhất được tạo ra từ con trai.' },
  { text: 'Trò gì càng chơi càng ra nước?', answer: 'Cờ vua', options: ['Cờ vua', 'Bơi lội', 'Kéo co', 'Trốn tìm'], explanation: 'Đây là một câu đố mẹo, "ra nước" ở đây là các nước đi trong cờ vua.' },
  { text: 'Nơi nào có đường xá, nhưng không có xe cộ?', answer: 'Bản đồ', options: ['Bản đồ', 'Sa mạc', 'Rừng sâu', 'Đại dương'], explanation: 'Trên bản đồ có vẽ các con đường nhưng không có xe thật chạy.' },
  { text: 'Cái gì bạn không mượn mà trả?', answer: 'Lời cảm ơn', options: ['Lời cảm ơn', 'Tiền bạc', 'Tình cảm', 'Đồ đạc'], explanation: 'Khi nhận được sự giúp đỡ, ta "trả" lại bằng lời cảm ơn.' },
  { text: 'Cái gì luôn đi đến mà không bao giờ đến nơi?', answer: 'Ngày mai', options: ['Ngày mai', 'Tương lai', 'Thời gian', 'Cơn gió'], explanation: 'Khi đến ngày mai, nó lại trở thành ngày hôm nay, và "ngày mai" lại là ngày tiếp theo.' },
  { text: 'Cái gì của bạn nhưng người khác dùng nhiều hơn bạn?', answer: 'Tên của bạn', options: ['Tên của bạn', 'Tiền của bạn', 'Nhà của bạn', 'Xe của bạn'], explanation: 'Người khác thường gọi tên bạn để xưng hô, còn bạn ít khi tự gọi tên mình.' },
  { text: 'Con gì mang được miếng gỗ lớn nhưng không mang được hòn sỏi?', answer: 'Con sông', options: ['Con sông', 'Con voi', 'Con kiến', 'Con trâu'], explanation: 'Con sông có thể cuốn trôi gỗ lớn nhưng hòn sỏi thì chìm xuống đáy.' },
  { text: 'Cái gì có kích thước bằng con voi nhưng chẳng nặng gram nào?', answer: 'Bóng con voi', options: ['Bóng con voi', 'Đám mây', 'Quả bóng bay', 'Mô hình voi'], explanation: 'Cái bóng chỉ là vùng tối, không có khối lượng.' },
  { text: 'Từ nào trong từ điển viết sai chính tả?', answer: 'Từ "sai"', options: ['Từ "sai"', 'Từ "đúng"', 'Không có từ nào', 'Từ "chính tả"'], explanation: 'Chính từ "sai" được viết là s-a-i.' },
  { text: 'Tôi có 4 chân nhưng không biết đi. Tôi là ai?', answer: 'Cái bàn', options: ['Cái bàn', 'Con chó', 'Con mèo', 'Cái ghế'], explanation: 'Cái bàn có 4 chân trụ nhưng là vật vô tri.' },
  { text: 'Có cổ nhưng không có đầu. Là cái gì?', answer: 'Cái áo', options: ['Cái áo', 'Cái chai', 'Con hươu', 'Cái bình'], explanation: 'Áo có phần cổ áo nhưng không có đầu người.' },
  { text: 'Có răng nhưng không cắn được ai. Là cái gì?', answer: 'Cái lược', options: ['Cái lược', 'Cái cưa', 'Con cá sấu', 'Bánh răng'], explanation: 'Răng lược dùng để chải tóc, không dùng để cắn.' },
  { text: 'Cái gì càng kéo càng ngắn?', answer: 'Điếu thuốc', options: ['Điếu thuốc', 'Sợi dây', 'Cái kẹo', 'Tuổi thọ'], explanation: 'Mỗi hơi kéo thuốc làm điếu thuốc ngắn lại vì bị cháy.' },
  { text: 'Cái gì đánh cha, đánh má, đánh anh, đánh chị?', answer: 'Bàn chải đánh răng', options: ['Bàn chải đánh răng', 'Cái roi', 'Cái chổi', 'Cái gậy'], explanation: 'Đây là cách chơi chữ, "đánh" ở đây là vệ sinh răng miệng.' },
  { text: 'Con mèo nào cực kỳ sợ chuột?', answer: 'Doraemon', options: ['Doraemon', 'Tom', 'Mèo máy', 'Mèo rừng'], explanation: 'Doraemon bị chuột gặm mất tai nên rất sợ chuột.' },
  { text: 'Người đàn ông duy nhất trên thế giới có sữa là ai?', answer: 'Ông Thọ', options: ['Ông Thọ', 'Bác sĩ', 'Người cha', 'Không có ai'], explanation: 'Sữa Ông Thọ là một thương hiệu sữa nổi tiếng.' },
  { text: 'Cái gì Adam có 2 mà Eva chỉ có 1?', answer: 'Chữ A', options: ['Chữ A', 'Con mắt', 'Cái tay', 'Quả táo'], explanation: 'Trong tên Adam có 2 chữ "a", Eva chỉ có 1 chữ "a".' },
  { text: 'Khi Beckham thực hiện quả đá phạt đền, anh ta sẽ sút vào đâu?', answer: 'Quả bóng', options: ['Quả bóng', 'Khung thành', 'Thủ môn', 'Lưới'], explanation: 'Muốn sút đi đâu thì trước tiên phải sút vào quả bóng.' },
  { text: 'Có bao nhiêu chữ C trong câu: "Cơm, canh, cháo gì tớ cũng thích ăn!"?', answer: '1 chữ C', options: ['1 chữ C', '2 chữ C', '3 chữ C', '4 chữ C'], explanation: 'Chỉ có chữ "C" viết hoa ở đầu câu, các chữ còn lại là "c" thường.' },
];

export const GENZ_QUESTIONS = [
  { text: 'Cái gì càng thiu càng ngon?', answer: 'Giấc ngủ', options: ['Giấc ngủ', 'Bánh mì', 'Cơm nguội', 'Canh chua'], explanation: 'Ngủ "thiu thiu" là trạng thái ngủ ngon và sâu.' },
  { text: 'Con gì sinh ra đã được làm vua?', answer: 'Con cua', options: ['Con cua', 'Con rồng', 'Con hổ', 'Con sư tử'], explanation: 'Cua có "ngang" (ngang tàng như vua) và có "càng" (vương trượng).' },
  { text: 'Cái gì càng cất càng thấy?', answer: 'Cái nhà', options: ['Cái nhà', 'Tiền bạc', 'Bí mật', 'Đồ ăn'], explanation: 'Xây (cất) nhà xong thì ngôi nhà hiện hữu rõ ràng.' },
  { text: 'Cái gì càng rửa càng bẩn?', answer: 'Nước', options: ['Nước', 'Cái chậu', 'Cái khăn', 'Cái tay'], explanation: 'Nước dùng để rửa đồ bẩn thì chính nước đó sẽ bị bẩn.' },
  { text: 'Trái gì không ăn được mà ai cũng sợ?', answer: 'Trái tính trái nết', options: ['Trái tính trái nết', 'Trái sầu riêng', 'Trái ớt', 'Trái mướp đắng'], explanation: 'Người có tính nết khó chịu (trái tính) thường khiến người khác e ngại.' },
  { text: 'Cái gì càng nặng càng nhẹ?', answer: 'Cái cân', options: ['Cái cân', 'Đám mây', 'Cái bóng', 'Kỷ niệm'], explanation: 'Khi vật càng nặng, kim cái cân càng di chuyển (nhẹ nhàng).' },
  { text: 'Cái gì càng thêm càng thiếu?', answer: 'Cái hố', options: ['Cái hố', 'Tiền bạc', 'Kiến thức', 'Tình cảm'], explanation: 'Càng đào thêm đất thì cái hố càng sâu và rộng (thiếu đất).' },
  { text: 'Cái gì càng cao càng thấp?', answer: 'Cái thang', options: ['Cái thang', 'Ngọn núi', 'Cái cây', 'Tòa nhà'], explanation: 'Khi bạn leo lên cao trên thang, khoảng cách tới đỉnh thang lại thấp dần.' },
  { text: 'Cái gì càng bẩn càng trắng?', answer: 'Cái bảng đen', options: ['Cái bảng đen', 'Cái áo', 'Cái răng', 'Cái gương'], explanation: 'Bảng đen càng nhiều vết phấn (bẩn) thì càng hiện màu trắng.' },
  { text: 'Cái gì càng gầy càng béo?', answer: 'Cái nến', options: ['Cái nến', 'Con heo', 'Cái cây', 'Con người'], explanation: 'Cây nến khi cháy mòn (gầy) thì sáp chảy ra xung quanh trông to hơn (béo).' },
  { text: 'Cái gì càng mất càng được?', answer: 'Kinh nghiệm', options: ['Kinh nghiệm', 'Tiền bạc', 'Thời gian', 'Sức khỏe'], explanation: 'Mất đi sai lầm thì ta được thêm kinh nghiệm quý báu.' },
  { text: 'Cái gì có mặt mà không có đầu?', answer: 'Đồng hồ', options: ['Đồng hồ', 'Cái bàn', 'Cái ghế', 'Cái gương'], explanation: 'Đồng hồ có mặt số nhưng không có bộ phận đầu.' },
  { text: 'Cái gì càng chạy càng đứng?', answer: 'Đồng hồ', options: ['Đồng hồ', 'Con người', 'Xe cộ', 'Dòng sông'], explanation: 'Đồng hồ chạy thời gian nhưng nó luôn đứng yên một chỗ.' },
  { text: 'Cái gì có chân mà không có tay, có thân mà không có đầu?', answer: 'Cái quần', options: ['Cái quần', 'Cái bàn', 'Cái ghế', 'Cây cối'], explanation: 'Quần có ống (chân), có thân quần nhưng không có đầu.' },
  { text: 'Cái gì càng tối càng sáng?', answer: 'Cái đèn', options: ['Cái đèn', 'Con mắt', 'Bầu trời', 'Bóng đêm'], explanation: 'Trong bóng tối, ánh đèn trông sẽ sáng và rõ ràng hơn.' },
  { text: 'Cái gì càng thắng càng thua?', answer: 'Đua xe đạp', options: ['Đua xe đạp', 'Kéo co', 'Bóng đá', 'Cờ vua'], explanation: 'Bóp thắng (phanh) làm xe đi chậm lại.' },
  { text: 'Cái gì càng chơi càng ra nước?', answer: 'Cờ vua', options: ['Cờ vua', 'Bơi lội', 'Kéo co', 'Trốn tìm'], explanation: 'Các "nước" đi trong bàn cờ.' },
  { text: 'Cái gì Adam có 2 mà Eva chỉ có 1?', answer: 'Chữ A', options: ['Chữ A', 'Con mắt', 'Cái tay', 'Quả táo'], explanation: 'Đếm số chữ "a" trong tên.' },
  { text: 'Từ nào trong từ điển viết sai chính tả?', answer: 'Từ "sai"', options: ['Từ "sai"', 'Từ "đúng"', 'Không có từ nào', 'Từ "chính tả"'], explanation: 'Chính là từ s-a-i.' },
  { text: 'Con mèo nào cực kỳ sợ chuột?', answer: 'Doraemon', options: ['Doraemon', 'Tom', 'Mèo máy', 'Mèo rừng'], explanation: 'Doraemon bị chuột gặm tai.' },
  { text: 'Cái gì càng kéo càng ngắn?', answer: 'Điếu thuốc', options: ['Điếu thuốc', 'Sợi dây', 'Cái kẹo', 'Tuổi thọ'], explanation: 'Điếu thuốc cháy ngắn lại.' },
  { text: 'Cái gì đánh cha, đánh má, đánh anh, đánh chị?', answer: 'Bàn chải đánh răng', options: ['Bàn chải đánh răng', 'Cái roi', 'Cái chổi', 'Cái gậy'], explanation: 'Đánh răng cho cả nhà.' },
  { text: 'Người đàn ông duy nhất trên thế giới có sữa là ai?', answer: 'Ông Thọ', options: ['Ông Thọ', 'Bác sĩ', 'Người cha', 'Không có ai'], explanation: 'Thương hiệu sữa Ông Thọ.' },
  { text: 'Cái gì đen khi mua, đỏ khi dùng, xám khi vứt?', answer: 'Than', options: ['Than', 'Củi', 'Giấy', 'Diêm'], explanation: 'Chu trình sử dụng than.' },
  { text: 'Cái gì có cổ nhưng không có đầu?', answer: 'Cái áo', options: ['Cái áo', 'Cái chai', 'Con hươu', 'Cái bình'], explanation: 'Cổ áo.' },
  { text: 'Cái gì có răng nhưng không cắn được ai?', answer: 'Cái lược', options: ['Cái lược', 'Cái cưa', 'Con cá sấu', 'Bánh răng'], explanation: 'Răng lược.' },
  { text: 'Cái gì càng già càng trẻ?', answer: 'Cái bóng', options: ['Cái bóng', 'Con người', 'Cái cây', 'Bức ảnh'], explanation: 'Cái bóng của người già hay trẻ đều trông như nhau.' },
  { text: 'Trái gì tên nghe đã thấy đau?', answer: 'Trái khổ qua', options: ['Trái khổ qua', 'Trái ớt', 'Trái sầu riêng', 'Trái mướp đắng'], explanation: 'Khổ qua = nỗi khổ đã qua, nhưng nghe từ "khổ" thấy đau.' },
  { text: 'Con gì không bao giờ biết đi?', answer: 'Con đường', options: ['Con đường', 'Con cá', 'Con rắn', 'Con chim'], explanation: 'Đường nằm yên cho người đi.' },
  { text: 'Cái gì có miệng mà không nói, có giường mà không ngủ?', answer: 'Con sông', options: ['Con sông', 'Cái hang', 'Cái hố', 'Cái chai'], explanation: 'Miệng sông và lòng (giường) sông.' },
];

export const PROVERB_QUESTIONS = [
  { text: 'Điền vào chỗ trống: "Gần mực thì đen, gần đèn thì..."', answer: 'Sáng', options: ['Sáng', 'Chói', 'Tối', 'Lòa'], explanation: 'Câu tục ngữ khuyên ta nên chọn môi trường tốt để học hỏi.' },
  { text: 'Điền vào chỗ trống: "Có công mài sắt, có ngày nên..."', answer: 'Kim', options: ['Kim', 'Dao', 'Kéo', 'Búa'], explanation: 'Kiên trì nhẫn nại sẽ gặt hái được thành công.' },
  { text: 'Điền vào chỗ trống: "Ăn quả nhớ kẻ trồng..."', answer: 'Cây', options: ['Cây', 'Hoa', 'Trái', 'Rừng'], explanation: 'Lòng biết ơn đối với những người đã tạo ra thành quả cho mình.' },
  { text: 'Điền vào chỗ trống: "Uống nước nhớ..."', answer: 'Nguồn', options: ['Nguồn', 'Suối', 'Sông', 'Biển'], explanation: 'Luôn nhớ về cội nguồn, tổ tiên.' },
  { text: 'Điền vào chỗ trống: "Tốt gỗ hơn tốt nước..."', answer: 'Sơn', options: ['Sơn', 'Màu', 'Bóng', 'Hoa'], explanation: 'Giá trị bên trong quan trọng hơn vẻ bề ngoài.' },
  { text: 'Điền vào chỗ trống: "Một con ngựa đau cả tàu bỏ..."', answer: 'Cỏ', options: ['Cỏ', 'Ăn', 'Chạy', 'Ngủ'], explanation: 'Tinh thần đoàn kết, tương thân tương ái.' },
  { text: 'Điền vào chỗ trống: "Cái nết đánh chết cái..."', answer: 'Đẹp', options: ['Đẹp', 'Xấu', 'Duyên', 'Tình'], explanation: 'Tính nết tốt quan trọng hơn vẻ đẹp hình thức.' },
  { text: 'Điền vào chỗ trống: "Đi một ngày đàng, học một sàng..."', answer: 'Khôn', options: ['Khôn', 'Dại', 'Sách', 'Chữ'], explanation: 'Đi ra ngoài trải nghiệm sẽ giúp ta mở mang kiến thức.' },
  { text: 'Điền vào chỗ trống: "Lá lành đùm lá..."', answer: 'Rách', options: ['Rách', 'Nát', 'Khô', 'Vàng'], explanation: 'Giúp đỡ những người khó khăn hơn mình.' },
  { text: 'Điền vào chỗ trống: "Gieo gió gặt..."', answer: 'Bão', options: ['Bão', 'Mưa', 'Nắng', 'Sấm'], explanation: 'Luật nhân quả: làm việc xấu sẽ nhận hậu quả nặng nề.' },
  { text: 'Điền vào chỗ trống: "Kiến tha lâu cũng đầy..."', answer: 'Tổ', options: ['Tổ', 'Nhà', 'Hang', 'Đất'], explanation: 'Chăm chỉ tích tiểu thành đại.' },
  { text: 'Điền vào chỗ trống: "Tức nước vỡ..."', answer: 'Bờ', options: ['Bờ', 'Đê', 'Đập', 'Chậu'], explanation: 'Sự chịu đựng có giới hạn, khi quá mức sẽ bùng phát.' },
  { text: 'Điền vào chỗ trống: "Ở hiền gặp..."', answer: 'Lành', options: ['Lành', 'Tốt', 'May', 'Phúc'], explanation: 'Người tốt sẽ gặp được những điều tốt đẹp.' },
  { text: 'Điền vào chỗ trống: "Áo mặc sao qua khỏi..."', answer: 'Đầu', options: ['Đầu', 'Cổ', 'Tay', 'Lưng'], explanation: 'Con cái nên nghe lời cha mẹ, bề dưới nên tôn trọng bề trên.' },
  { text: 'Điền vào chỗ trống: "Con hơn cha là nhà có..."', answer: 'Phúc', options: ['Phúc', 'Lộc', 'Tài', 'Đức'], explanation: 'Sự tiến bộ của thế hệ sau là niềm tự hào của gia đình.' },
  { text: 'Điền vào chỗ trống: "Giỏ nhà ai quai nhà..."', answer: 'Nấy', options: ['Nấy', 'Đ đó', 'Kia', 'Này'], explanation: 'Con cái thường thừa hưởng tính cách từ cha mẹ.' },
  { text: 'Điền vào chỗ trống: "Tránh vỏ dưa gặp vỏ..."', answer: 'Dừa', options: ['Dừa', 'Chuối', 'Cam', 'Bưởi'], explanation: 'Tránh được cái rủi này lại gặp cái rủi khác tương tự.' },
  { text: 'Điền vào chỗ trống: "Thất bại là mẹ..."', answer: 'Thành công', options: ['Thành công', 'Chiến thắng', 'Kinh nghiệm', 'Bài học'], explanation: 'Từ thất bại ta rút ra bài học để thành công.' },
  { text: 'Điền vào chỗ trống: "Nước mắt chảy..."', answer: 'Xuôi', options: ['Xuôi', 'Ngược', 'Tràn', 'Dài'], explanation: 'Tình thương của cha mẹ luôn dành cho con cái vô điều kiện.' },
  { text: 'Điền vào chỗ trống: "Môi hở răng..."', answer: 'Lạnh', options: ['Lạnh', 'Buốt', 'Đau', 'Rụng'], explanation: 'Anh em, người thân phải đùm bọc lẫn nhau.' },
  { text: 'Điền vào chỗ trống: "Lửa thử vàng, gian nan thử..."', answer: 'Sức', options: ['Sức', 'Tài', 'Trí', 'Lòng'], explanation: 'Khó khăn là thước đo bản lĩnh con người.' },
  { text: 'Điền vào chỗ trống: "Thuận vợ thuận chồng tát biển Đông cũng..."', answer: 'Cạn', options: ['Cạn', 'Khô', 'Vơi', 'Hết'], explanation: 'Sự đồng lòng trong gia đình tạo nên sức mạnh to lớn.' },
  { text: 'Điền vào chỗ trống: "Ăn vóc học..."', answer: 'Hay', options: ['Hay', 'Tài', 'Giỏi', 'Khôn'], explanation: 'Có sức khỏe để làm việc và có kiến thức để thành công.' },
  { text: 'Điền vào chỗ trống: "Học thầy không tày học..."', answer: 'Bạn', options: ['Bạn', 'Sách', 'Đời', 'Trường'], explanation: 'Học hỏi từ bạn bè cũng rất quan trọng.' },
  { text: 'Điền vào chỗ trống: "Trăm hay không bằng tay..."', answer: 'Quen', options: ['Quen', 'Làm', 'Giỏi', 'Nhanh'], explanation: 'Lý thuyết giỏi không bằng thực hành nhiều.' },
  { text: 'Điền vào chỗ trống: "Lời nói gói..."', answer: 'Vàng', options: ['Vàng', 'Bạc', 'Tiền', 'Ngọc'], explanation: 'Lời nói có giá trị rất lớn, nên cẩn trọng.' },
  { text: 'Điền vào chỗ trống: "Chim có tổ, người có..."', answer: 'Tông', options: ['Tông', 'Nhà', 'Quê', 'Cội'], explanation: 'Ai cũng có cội nguồn, tổ tiên.' },
  { text: 'Điền vào chỗ trống: "Đói cho sạch, rách cho..."', answer: 'Thơm', options: ['Thơm', 'Lành', 'Đẹp', 'Mới'], explanation: 'Dù khó khăn vẫn phải giữ gìn nhân cách.' },
  { text: 'Điền vào chỗ trống: "Giấy rách phải giữ lấy..."', answer: 'Lề', options: ['Lề', 'Góc', 'Mép', 'Chữ'], explanation: 'Giữ gìn truyền thống, nề nếp gia đình.' },
  { text: 'Điền vào chỗ trống: "Một cây làm chẳng nên..."', answer: 'Non', options: ['Non', 'Rừng', 'Núi', 'Cảnh'], explanation: 'Cá nhân đơn lẻ khó làm nên việc lớn.' },
  { text: 'Điền vào chỗ trống: "Ba cây chụm lại nên hòn núi..."', answer: 'Cao', options: ['Cao', 'To', 'Lớn', 'Đẹp'], explanation: 'Sức mạnh của sự đoàn kết.' },
  { text: 'Điền vào chỗ trống: "Bán anh em xa mua láng giềng..."', answer: 'Gần', options: ['Gần', 'Thân', 'Tốt', 'Quen'], explanation: 'Quan hệ hàng xóm láng giềng rất quan trọng trong cuộc sống.' },
  { text: 'Điền vào chỗ trống: "Lên thác xuống..."', answer: 'Ghềnh', options: ['Ghềnh', 'Đèo', 'Suối', 'Sông'], explanation: 'Trải qua nhiều gian nan, vất vả.' },
  { text: 'Điền vào chỗ trống: "Mật ngọt chết..."', answer: 'Ruồi', options: ['Ruồi', 'Kiến', 'Ong', 'Muỗi'], explanation: 'Những lời nịnh nọt thường ẩn chứa nguy hiểm.' },
  { text: 'Điền vào chỗ trống: "Chớp đông nhay nháy, gà gáy thì..."', answer: 'Mưa', options: ['Mưa', 'Nắng', 'Bão', 'Gió'], explanation: 'Kinh nghiệm dự báo thời tiết của ông cha ta.' },
  { text: 'Điền vào chỗ trống: "Chuồn chuồn bay thấp thì mưa, bay cao thì nắng, bay vừa thì..."', answer: 'Râm', options: ['Râm', 'Mát', 'Gió', 'Bão'], explanation: 'Dựa vào độ cao bay của chuồn chuồn để đoán thời tiết.' },
  { text: 'Điền vào chỗ trống: "Cơn đằng Đông vừa trông vừa chạy, cơn đằng Nam vừa làm vừa..."', answer: 'Chơi', options: ['Chơi', 'Nghỉ', 'Hát', 'Cười'], explanation: 'Mây đằng Đông thường kéo theo mưa nhanh.' },
  { text: 'Điền vào chỗ trống: "Lúa chiêm lấp ló đầu bờ, hễ nghe tiếng sấm phất cờ mà..."', answer: 'Lên', options: ['Lên', 'Trổ', 'Chín', 'Mọc'], explanation: 'Mưa giông kèm sấm sét cung cấp đạm cho lúa phát triển.' },
  { text: 'Điền vào chỗ trống: "Đêm tháng năm chưa nằm đã sáng, ngày tháng mười chưa cười đã..."', answer: 'Tối', options: ['Tối', 'Khóc', 'Buồn', 'Ngủ'], explanation: 'Sự thay đổi độ dài ngày đêm theo mùa.' },
  { text: 'Điền vào chỗ trống: "Gió heo may, chuồn chuồn bay thì..."', answer: 'Bão', options: ['Bão', 'Mưa', 'Nắng', 'Rét'], explanation: 'Dấu hiệu thời tiết chuyển mùa.' },
];

